
import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
from mimic_real.assets import ISAAC_ASSET_DIR

HI_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=f"{ISAAC_ASSET_DIR}/usd/high_torque/hi_massfixed/hi.usd",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True, solver_position_iteration_count=4, solver_velocity_iteration_count=4
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.46),
        joint_pos={            
            "waist_joint": 0.0, 
            ".*_shoulder_pitch_joint": 0.0,
            ".*_shoulder_roll_joint": 0.0,
            ".*_upper_arm_joint": 0.0,
            ".*_elbow_joint": 0.0,
            ".*_wrist_joint": 0.0,
            ".*_hip_pitch_joint": 0.0,
            ".*_hip_roll_joint": 0.0,
            ".*_thigh_joint": 0.0,
            ".*_calf_joint": 0.0,
            ".*_ankle_pitch_joint": 0.0,
            ".*_ankle_roll_joint": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor = 0.95,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                "waist_joint", 
                ".*_shoulder_pitch_joint",
                ".*_shoulder_roll_joint",
                ".*_upper_arm_joint",
                ".*_elbow_joint",
                ".*_wrist_joint",
                ".*_hip_pitch_joint",
                ".*_hip_roll_joint",
                ".*_thigh_joint",
                ".*_calf_joint",
                ".*_ankle_pitch_joint",
                ".*_ankle_roll_joint",
            ],
            effort_limit_sim={
                "waist_joint": 24.0, 
                ".*_shoulder_pitch_joint": 17.0,
                ".*_shoulder_roll_joint": 17.0,
                ".*_upper_arm_joint": 17.0,
                ".*_elbow_joint": 17.0,
                ".*_wrist_joint": 17.0,
                ".*_hip_pitch_joint": 24.0,
                ".*_hip_roll_joint": 24.0,
                ".*_thigh_joint": 24.0,
                ".*_calf_joint": 24.0,
                ".*_ankle_pitch_joint": 24.0,
                ".*_ankle_roll_joint": 24.0,
            },
            velocity_limit_sim={
                "waist_joint": 6.28, 
                ".*_shoulder_pitch_joint": 6.28,
                ".*_shoulder_roll_joint": 6.28,
                ".*_upper_arm_joint": 6.28,
                ".*_elbow_joint": 6.28,
                ".*_wrist_joint": 6.28,
                ".*_hip_pitch_joint": 6.28,
                ".*_hip_roll_joint": 6.28,
                ".*_thigh_joint": 6.28,
                ".*_calf_joint": 6.28,
                ".*_ankle_pitch_joint": 6.28,
                ".*_ankle_roll_joint": 6.28,
            },
            stiffness={
                "waist_joint": 80.0, 
                ".*_shoulder_pitch_joint": 80.0,
                ".*_shoulder_roll_joint": 80.0,
                ".*_upper_arm_joint": 80.0,
                ".*_elbow_joint": 80.0,
                ".*_wrist_joint": 80.0,
                ".*_hip_pitch_joint": 80.0,
                ".*_hip_roll_joint": 80.0,
                ".*_thigh_joint": 80.0,
                ".*_calf_joint": 80.0,
                ".*_ankle_pitch_joint": 80.0,
                ".*_ankle_roll_joint": 80.0,
            },
            damping={
                "waist_joint": 1.0, 
                ".*_shoulder_pitch_joint": 1.0,
                ".*_shoulder_roll_joint": 1.0,
                ".*_upper_arm_joint": 1.0,
                ".*_elbow_joint": 1.0,
                ".*_wrist_joint": 1.0,
                ".*_hip_pitch_joint": 1.0,
                ".*_hip_roll_joint": 1.0,
                ".*_thigh_joint": 1.0,
                ".*_calf_joint": 1.0,
                ".*_ankle_pitch_joint": 1.0,
                ".*_ankle_roll_joint": 1.0,
            },
        ),
    },
)